server:
  port: 8060

spring:
  application:
    name: cloud-seata-order

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    alibaba:
      seata:
        # 自定义事务组名称需要与seata-server中的对应
        tx-service-group: litway_tx_group

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/learn-seata-order
    username: root
    password: root

feign:
  hystrix:
    enabled: true

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml



