server:
  port: 8060

spring:
  application:
    name: cloud-seata-order

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    alibaba:
      seata:
        # 自定义事务组名称需要与seata-server中的对应
        tx-service-group: litway_tx_group

  datasource:
    # 8.0mysql驱动配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/learn-seata-order?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: root

    # 这是5.7的驱动配置, springboot 2.2.2使用的是8.0的驱动, 所以配置不对
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/learn-seata-order
#    username: root
#    password: root

feign:
  hystrix:
    enabled: true

logging:
  level:
    io:
      seata: info

    # mybatis日志, 对这个包起作用
    com:
      litway:
        springcloud:
          mapper: debug
mybatis:
  mapperLocations: classpath:mapper/*.xml



