server:
  port: 8060

spring:
  application:
    name: cloud-seata-order

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    alibaba:
      seata:
        # 自定义事务组名称需要与seata-server中的对应
        tx-service-group: litway_tx_group

  datasource:
    # 8.0mysql驱动配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/learn-seata-order?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: root

    # 这是5.7的驱动配置, springboot 2.2.2使用的是8.0的驱动, 所以配置不对
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/learn-seata-order
#    username: root
#    password: root

# 开启了此处, 会导致hystrix的默认超时时间为1s, 并且还会和ribbon的超时时间同时生效, 那么下面的ribbon就起不到了作用
# ribbon和feign的超时时间是相互制约的, 如果都配置则只有feign的生效
# 参考: https://blog.csdn.net/w55935/article/details/126158124
#feign:
#  hystrix:
#    enabled: true

# 延长调用时间
ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 2000

logging:
  level:
    io:
      seata: info

    # mybatis日志, 对这个包起作用
    com: debug


mybatis:
  mapperLocations: classpath:mapper/*.xml



