server:
  port: 3344

spring:
  application:
    name: cloud-config-center

  # cloud
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # 注册到consul注册中心的名称
        service-name: ${spring.application.name}

    # springcloud config相关配置
    config:
      server:
        git:
          # Config需要读取远程Git仓库的配置信息, 因此需要给出git地址
          uri: git@github.com:Litway0517/SpringCloud_Code2020.git
          # 仅仅地址不够, 还需要指明路径
          search-paths:
            - SpringCloud_Code2020/cloud-config-server/src/main/resources/

