server:
  port: 8006

spring:
  application:
    name: consul-provider-payment

  # consul注册中心
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # hostname
        service-name: ${spring.application.name}

  # 数据源
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动包 com.mysql.jdbc.Driver
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/sgg-springcloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root


mybatis:
  mapperLocations: classpath:mapper/*.xml
  # 所有Entity别名类所在包
  type-aliases-package: com.atguigu.springcloud.entities
