server:
  port: 9527

spring:
  application:
    name: cloud-gateway

  # cloud
  cloud:
    # 注册到consul
    consul:
      host: localhost
      port: 8500
      discovery:
        # 服务名称
        service-name: ${spring.application.name}

    # 网关相关配置
    gateway:
      discovery:
        locator:
          # 开启根据 注册中心的微服务名称 动态创建路由的功能
          enabled: true

      routes:
        # 路由的ID，没有固定规则但要求唯一，建议配合服务名
        - id: consul-provider-payment-routh-1
          # 匹配路由成功后, 提供服务的路由地址
          # uri: http://localhost:8006
          uri: lb://consul-provider-payment
          # 断言. 与此断言相匹配的路由路径才进行路由
          predicates:
            # Path -> PathRoutePredicate 路径断言. 即在consul-provider-payment微服务下存在该通配的路径
            - Path=/payment/get/**

            # After -> AfterRoutePredicate after断言. 请求需要在此时间之后
            - After=2022-09-23T16:32:03.344+08:00[Asia/Shanghai]

            # Before -> BeforeRoutePredicate before断言. 请求需要在此时间之前
            # - Before=2022-09-23T16:32:03.344+08:00[Asia/Shanghai]

            # Between -> BetweenRoutePredicate between断言. 请求需要在此时间之间
            # - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver]

            # Cookie -> CookieRoutePredicate. 要求请求的请求头中需要携带cookie指定的键值对. key=username, value=litway
            - Cookie=username,litway

            # Header -> HeaderRoutePredicate. 检查请求的请求头中是否携带指定的值. 要求请求头携带X-Request-Id值, 且为正整数
            - Header=X-Request-Id, \d+

            # Query -> QueryRoutePredicate. 表示请求路径中需要携带red参数, 参数的值可以是gree green, 这是一个正则
            - Query=red, gree.

        # 第二组配置
        - id: consul-provider-payment-routh-1
          # uri: http://localhost:8006
          uri: lb://consul-provider-payment
          predicates:
            - Path=/payment/consul


