server:
  port: 80

spring:
  application:
    name: consul-provider-payment

  # consul注册中心
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # 服务名称
        service-name: ${spring.application.name}


