server:
  port: 9002

spring:
  application:
    name: nacos-provider-payment


  cloud:
    # nacos相关
    nacos:
      discovery:
        # nacos地址, 本模块将会注册到下面的地址
        server-addr: http://localhost:8848


management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
