server:
  port: 9002

spring:
  application:
    name: nacos-provider-payment


  cloud:
    # nacos相关
    nacos:
      discovery:
        # nacos地址, 本模块将会注册到下面的地址
        # server-addr: http://localhost:8848/
        # nacos集群, 注册中心地址改成Linux服务器上面的nginx虚拟端口, nginx负责反向代理路由转发
        server-addr: 192.168.62.131:8090


management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
