server:
  port: 80


spring:
  application:
    name: cloud-consumer-hystrix-order

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # 注册空间地址
        namespace: 36df2268-32ce-4f11-95bc-e3d92a1e025e


# 配置OpenFeign的超时调用
#feign:
#  hystrix:
#    enabled: true

ribbon:
  # RPC调用超时
  ConnectTimeout: 5000
  ReadTimeout: 5000
